"""Add the library table

Revision ID: ee5c9117b71f
Revises: 
Create Date: 2022-06-08 17:48:27.862811

"""
from alembic import op
import sqlalchemy as sa

# This is needed for the Web2PyBoolean class.
import bookserver.models


# revision identifiers, used by Alembic.
revision = "ee5c9117b71f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("subtitle", sa.String(length=512), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("authors", sa.Text(), nullable=True),
        sa.Column("shelf_section", sa.String(length=512), nullable=True),
        sa.Column("basecourse", sa.String(length=512), nullable=True),
        sa.Column("build_system", sa.String(length=20)),
        sa.Column("for_classes", bookserver.models.Web2PyBoolean()),
        sa.Column("is_visible", bookserver.models.Web2PyBoolean(), default="T"),
        sa.Column("github_url", sa.String(length=512)),
        sa.Column("main_page", sa.String(length=512), default="index.html"),
        sa.Column("last_build", sa.DateTime()),
        sa.Column("github_url", sa.String(length=255)),
        sa.ForeignKeyConstraint(
            ["basecourse"],
            ["courses.course_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("library")
    # ### end Alembic commands ###
